.Dd April 27, 2015
.Dt SDHCP 1
.Os
.Sh NAME
.Nm sdhcp
.Nd a simple DHCP client
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl e Ar program
.Op Fl f
.Op Fl i
.Op Ar interface
.Op Ar client-id
.Sh DESCRIPTION
.Nm
is a simple, tiny DHCP client. It runs until it enters the "Bound"
state, then forks to the background and runs as a daemon to keep
the lease alive.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
don't change DNS in
.Pa /etc/resolv.conf .
.It Fl e Ar program
run
.Ar program .
Variables will be set, see VARIABLES.
.It Fl f
run in foreground.
.It Fl i
don't change interface information such as an IP address.
.El
.Sh VARIABLES
The following variables are set:
.Bl -tag -width Ds
.It Ev SERVER
DHCP IP.
.It Ev DNS
DNS IP.
.It Ev ROUTER
router IP.
.It Ev MASK
network mask.
.It Ev CLIENT
your client IP.
.El
.Sh BUGS
I'm sure there are plenty. It only currently supports a small subset of
DHCP options, and has been untested on larger networks. It ignores most of
the DHCP options it understands.
