.Dd April 27, 2015
.Dt SDHCP 1
.Os
.Sh NAME
.Nm sdhcp
.Nd a simple DHCP client
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl e Ar program
.Op Fl f
.Op Fl i
.Op Fl r Ar resolv.conf file
.Op Ar interface
.Op Ar client-id
.Sh DESCRIPTION
.Nm
is a simple, tiny DHCP client. It runs until it enters the "Bound"
state, then forks to the background and runs as a daemon to keep
the lease alive.

The
.Pa client-id
is a series of hex bytes. If you don't specify a
.Pa client-id
then it defaults to your hardware (MAC) address. The
.Pa client-id
is usually a DHCP Unqiue Identifier (DUID).
If you are connecting to an internet provider and your DHCP address
changes on every bind, you probably should set the
.Pa client-id.

.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
don't change DNS in
.Pa /etc/resolv.conf .
.It Fl e Ar program
run
.Ar program .
Variables will be set, see VARIABLES.
.It Fl f
run in foreground.
.It Fl i
don't change interface information such as an IP address.
.It Fl r Ar resolv.conf file
alternate /etc/resolv.conf location
.El
.Sh VARIABLES
The following variables are set:
.Bl -tag -width Ds
.It Ev CLIENT
your client IP.
.It Ev IFNAME
interface name.
.It Ev LEASE
lease time.
.It Ev MASK
network mask.
.It Ev ROUTER
router (gateway) IP.
.It Ev SERVER
DHCP server IP.
.It Ev SPID
shdcp pid.
.It Ev STATE
BOUND or RENEW.
.El

The following variables are set if provided by the server:
.Bl -tag -width Ds
.It Ev DNS
DNS IP.
.It Ev DNS2
alternate DNS IP.
.It Ev DOMAIN
domain name.
.It Ev NTP
NTP IP.
.It Ev NTP2
alternate NTP IP.
.El
.Sh BUGS
I'm sure there are plenty. It only currently supports a small subset of
DHCP options, and has been untested on larger networks. It ignores most of
the DHCP options it understands.
