#!/bin/sh

TMP=/tmp/NETWORKING
echo $0 $* >> $TMP

# The last arg should be the interface
for arg; do :; done

if [ $arg = eth0 ]; then
	if [ $1 = "--allow=hotplug" ]; then
		exit 0 # do nothing
	fi
	if ps ax | fgrep sdhcp | fgrep -q eth0; then
		logger "sdhcp eth0 already running"
		exit 0
	fi
	
	echo "Starting sdhcp..." >> $TMP # SAM DBG
	/sbin/sdhcp -d -e /etc/sdhcp-script eth0 && exit 0
fi

# Let Ubuntu deal with it
echo $0 UBUNTU >> $TMP # SAM DBG
/sbin/ifup $*
